### PR TITLE
Add Support for Checkstyle To gateway.server.api module

### PR DESCRIPTION
**Pull request by nowucca**
# Common Style Issues observed
* copyright header is not consistent with required code.quality, fixed to make comma optional
* trailing spaces inside the license text at the top of each file should be fixed globally
* many errors are simply trailing-whitespace lines; perl-pi.bak -e 's#(\s+)\n#\n#g' fixes most issues

# Decision to CheckStyle at Build Time
* checking at build-time is a good way to enforce standards, and they do not seem too burdensome.
* other Kaazing projects do this
* there is a design question about whether to use a local checkstyle.xml file for each repository (duplication) or whether to use a URL-based checkstyle.xml (introduces netowrk dependency to build).  I've opted for a local checkstyle.xml in these commits as the lesser of these evils, but I'm happy for anyone to revisit that decision.

### CODE REVIEW

**Comment by jfallows** [comment]
@nowucca, would you mind updating this to use the code.quality checkstyle.xml as a dependency instead of the local checkstyle.xml file?

We still need to go through the projects and move them all to the consistent definition in code.quality where it can centrally be updated if we decide to make changes.

**Comment by nowucca** [comment]
John,


Happy to do that, the downside is it introduces a build time dependency on github being accessible if I use an http url.  If I use a file-based url or relative path it imposes structure on one's dev layout.




But I'll do it because it seems one source of truth is paramount.....going with the http solution, unless you object.




Steve








—

**Comment by nowucca** [comment]
Updated to use central code.quality checkstyle location: https://raw.githubusercontent.com/kaazing/code.quality/develop/src/main/resources/org/kaazing/code/quality/checkstyle.xml

Ready to merge now.

**Comment by jfallows** [comment]
@nowucca: let's see if we can have our cake and eat it too... :smile: 

The [kaazing/netx.http](https://github.com/kaazing/netx.http) project builds offline with `mvn -o clean verify` and it also uses the `code.quality` dependency.

Take a look and see if you think this approach would work for `gateway.server.api` as well.

**Comment by nowucca** [comment]
@jfallows Thanks for the tip, the approach is very solid and I applied it to gateway.server.api.  
* The branch failed checks because we depend on code.quality 1.1-SNAPSHOT in this checkin.  We should release code.quality 1.1 when you think it is ready, and then update this dependency in this pom.xml
* The license plugin uses the community.license' COPYRIGHT header, which does NOT include the copyright notice comma, so attempting to appease checkstyle by adding the commas then causes the license validation to fail.
* I checked that if we add the comma and release community.license, community, common we COULD enforce a mandatory comma in the COPYRIGHT template.  This is NOT the way forward though, because we should not REQUIRE the comma and all the existing files in gateway.* repositories do not have the comma.

**Comment by jfallows** [comment]
Thanks @nowucca!

I'll assign this to @dpwspoon so he can coordinate the release of code.quality 1.1 first.

**Comment by dpwspoon** [comment]
code.quality 1.1 should be released, restarting travis ci builds now

**Comment by dpwspoon** [comment]
Actually @nowucca, can you remove the SNAPSHOT dependency and confirm its all good.  -Thanks

**Comment by nowucca** [comment]
Yeah sorry about that.  Versioning can be annoying.  Sneak it in later today....

—

**Comment by nowucca** [comment]
All fixed, Travis build is good. Thanks.

**Comment by jfallows** [comment]
Thanks @nowucca !

**Pull request merged**
